### ISSUE TITLE
Killing local blockscout process also kills VS code and Slack

### ISSUE THREAD

**Issue by Lorune** [poanetwork/blockscout-terraform#117]
During the software deployment process a local blockscout server is started up and the killing of this local ran installation also kills any running instances of Visual studio code and Slack, forcing you to restart them.

**Comment by ArseniiPetrovich** [comment]
This seems to occur because of the method we kill the Phoenix server. @vbaranov, I suppose you have the Slack on the Mac where you deploy the BS? If so, could you please run the local server instance and find those PKill command that terminates the BS instance and doesn't terminate the Slack at the same time.
